name: 'Docker composite action'
description: 'A composite action to handle building a Docker image'

env:
  namespace:  PLACEHOLDER             # TODO: REPLACE WITH: drone | bin | gcs ...
  conan:      PLACEHOLDER             # TODO: REPLACE WITH: true | false
  arch:       linux/amd64,linux/arm64 # TODO: replace with correct arch
  
inputs:
  namespace:          # drone | bin | gcs ...
    required: true
    description: 'The modules namespace'
  conan:
    required: false
    description: 'Whether the image contains a conan package or not'
    default: false
  arch:
    required: true
    description: 'The architucture to build the image for'
    default: linux/amd64,linux/arm64
  registry:
    required: true
    description: 'The registry URL'
  username:
    required: true
    description: 'The registry user name'
  password:
    required: true
    description: 'The registry password'
  qemu_image:
    required: false
    description: 'qemu image to use'
    default: tonistiigi/binfmt:latest
  new_tag:
    required: true
    description: 'The new tag to push'
  dockerfile:
    required: true
    description: 'The dockerfile to build'
    default: ./Dockerfile
  branch:
    required: true
    description: 'The repo's branch'
    default: ${GITHUB_REF#refs/heads/}
  previous_light_tag:
    required: false
    description: 'previous lightweight tag'
outputs:
  url:
    description: 'The URL of the new image'
    value: ${{ inputs.registry }}/reg/${{ inputs.namespace }}/${{ github.event.repository.name }}:${{ inputs.new_tag }},${{ inputs.registry }}/reg/${{ inputs.namespace }}/${{ github.event.repository.name }}:${{ inputs.branch }}
  digest:
    description: 'The digest of the new image'
    value: ${{ steps.build.outputs.digest }}
  
runs:
    using: "composite"
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: ${{ inputs.qemu_image }}
          platforms: all
          
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Configure docker buildx
        uses: teveltech/buildx-action@master
          
      - name: Login to Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ inputs.registry }}
          username: ${{ inputs.username }} 
          password: ${{ inputs.password }}
          
      - name: Override version in conanpackage.py
        if: ${{ inputs.conan == 'true' }}
        uses: teveltech/version-action@master
        with:
          new_version: ${{ inputs.new_tag }}
          
      - name: Build
        id: build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ inputs.dockerfile }}
          platforms: ${{ inputs.arch }}
          pull: true
          push: true
          tags: ${{ inputs.registry }}/reg/${{ inputs.namespace }}/${{ github.event.repository.name }}:${{ inputs.new_tag }},${{ inputs.registry }}/reg/${{ inputs.namespace }}/${{ github.event.repository.name }}:${{ inputs.branch }}
          cache-from: type=registry,ref=${{ inputs.registry }}/reg/${{ inputs.namespace }}/${{ github.event.repository.name }}:${{ inputs.previous_light_tag }}
          cache-to: type=inline
