name: 'Docker composite action'
description: 'A composite action to handle building a Docker image'
  
inputs:
  namespace:          # drone | bin | gcs ...
    required: true
    description: 'The module namespace'
#   conan:
#     required: false
#     description: 'Whether the image contains a conan package or not'
#     default: false
  platforms:
    required: true
    description: 'The architucture to build the image for'
#     default: linux/amd64,linux/arm64
  registry:
    required: true
    description: 'The registry URL'
  username:
    required: true
    description: 'The registry user name'
  password:
    required: true
    description: 'The registry password'
#   qemu-image:
#     required: false
#     description: 'qemu image to use'
# #     default: tonistiigi/binfmt:latest
  new-tag:
    required: true
    description: 'The new tag to push'
  dockerfile:
    required: true
    description: 'The dockerfile to build'
    default: ./Dockerfile
  branch:
    required: true
    description: 'The repo branch'
  previous-light-tag:
    required: false
    description: 'previous lightweight tag'
  build-args:
    required: false
    description: 'docker build arguments'
  package-folder:
    required: true
    description: 'Path to package.json / setup.py / conanfile.py / Chart.yaml'
    default: './'
  secrets:
    required: false
    description: 'secrets to pass to docker'
    
outputs:
  image:
    description: 'The name and tag of the new image'
    value: ${{ github.event.repository.name }}:${{ inputs.new-tag }}
  url:
    description: 'The URL of the new image'
    value: ${{ inputs.registry }}/reg/${{ inputs.namespace }}/${{ github.event.repository.name }}:${{ inputs.new-tag }}
  digest:
    description: 'The digest of the new image'
    value: ${{ steps.build.outputs.digest }}
  package:
    value: jfrog.local:8081/reg/${{ inputs.namespace }}/${{ github.event.repository.name }}:${{ inputs.new-tag }}
  command:
    value: docker pull jfrog.local:8081/reg/${{ inputs.namespace }}/${{ github.event.repository.name }}:${{ inputs.new-tag }}
  
runs:
    using: "composite"
    steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - name: Checkout
#         uses: actions/checkout@v2
#         with:
#           persist-credentials: false

      - name: Override version in package.json / setup.py / conanfile.py / Chart.yaml
#         if: ${{ inputs.conan == 'true' }}
        uses: teveltech/version-action@no-fail
        with:
          new_version: ${{ inputs.new-tag }}
          file_path: ${{ inputs.package-folder }}
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
#           image: ${{ inputs.qemu-image }}
          image: ${{ inputs.registry }}/reg/base/tonistiigi/binfmt:latest
          platforms: all
          
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Configure docker buildx
        uses: teveltech/buildx-action@master
          
      - name: Login to Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ inputs.registry }}
          username: ${{ inputs.username }} 
          password: ${{ inputs.password }}
          
      - name: Build
        id: build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ inputs.dockerfile }}
          platforms: ${{ inputs.platforms }}
          pull: true
          push: true
          tags: |
            ${{ inputs.registry }}/reg/${{ inputs.namespace }}/${{ github.event.repository.name }}:${{ inputs.new-tag }}
            ${{ inputs.registry }}/reg/${{ inputs.namespace }}/${{ github.event.repository.name }}:${{ inputs.branch }}
          cache-from: type=registry,ref=${{ inputs.registry }}/reg/${{ inputs.namespace }}/${{ github.event.repository.name }}:${{ inputs.previous-light-tag }}
          cache-to: type=inline
          build-args: ${{ inputs.build-args }}
          secrets: ${{ inputs.secrets }}
